"""Run replay validation using multi-UAV trajectories generated by gym-pybullet-drones."""

from __future__ import annotations

import json
import math
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))

from passive_localization.config import MethodConfig
from passive_localization.pybullet_bridge import PyBulletReplayConfig, generate_pybullet_replay_cases
from passive_localization.replay import evaluate_replay_case, summarize_replay_results


def _sign_test_p_value(wins: int, losses: int) -> float:
    total = wins + losses
    if total == 0:
        return 1.0
    k = min(wins, losses)
    tail = sum(math.comb(total, idx) for idx in range(0, k + 1)) / (2**total)
    return float(min(1.0, 2.0 * tail))


def _paired_report(rows: list[dict], left: str, right: str) -> dict[str, float | int]:
    left_vals = np.array([row["results"][left]["error"] for row in rows], dtype=float)
    right_vals = np.array([row["results"][right]["error"] for row in rows], dtype=float)
    improvement = right_vals - left_vals
    wins = int(np.sum(improvement > 0.0))
    losses = int(np.sum(improvement < 0.0))
    ties = int(np.sum(np.isclose(improvement, 0.0)))
    return {
        "wins": wins,
        "losses": losses,
        "ties": ties,
        "sign_test_p_value": _sign_test_p_value(wins, losses),
        "median_improvement": float(np.median(improvement)),
        "mean_improvement": float(np.mean(improvement)),
    }


def run_pybullet_replay_validation(
    output_dir: str | Path = "experiments",
    seeds: list[int] | None = None,
) -> dict:
    seeds = list(seeds or [0, 1, 2])
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    regimes = {
        "nominal_pybullet": {
            "target_x": 0.0,
            "target_y": 0.0,
            "position_scale": 10.0,
            "duration_sec": 7.0,
            "warmup_sec": 2.0,
            "sample_every": 3,
            "common_bias": 0.0065,
            "bias_drift": 0.0022,
            "noise_std": 0.0048,
            "attitude_gain": 0.017,
            "yaw_rate_gain": 0.0016,
            "fov_half_angle_deg": 105.0,
            "delay_steps_mean": 0.45,
            "delay_steps_std": 0.22,
            "missing_rate": 0.010,
            "outlier_rate": 0.010,
            "outlier_scale": 0.08,
            "gust_force_std": 0.13,
            "gust_probability": 0.24,
            "gust_interval_steps": 6,
        },
        "disturbed_pybullet": {
            "target_x": 0.0,
            "target_y": 0.0,
            "position_scale": 10.0,
            "duration_sec": 7.5,
            "warmup_sec": 2.0,
            "sample_every": 3,
            "common_bias": 0.009,
            "bias_drift": 0.003,
            "noise_std": 0.006,
            "attitude_gain": 0.020,
            "yaw_rate_gain": 0.0020,
            "fov_half_angle_deg": 105.0,
            "delay_steps_mean": 0.60,
            "delay_steps_std": 0.28,
            "missing_rate": 0.015,
            "outlier_rate": 0.016,
            "outlier_scale": 0.12,
            "gust_force_std": 0.16,
            "gust_probability": 0.30,
            "gust_interval_steps": 6,
        },
    }
    formations = ["circle", "ellipse"]
    counts = [8, 10]

    method_config = MethodConfig()
    rows_by_regime: dict[str, list[dict]] = {name: [] for name in regimes}
    rows_by_group: dict[str, list[dict]] = {}
    example_traces: dict[str, dict] = {}
    meta_runs: list[dict] = []

    for regime_name, regime_kwargs in regimes.items():
        for formation in formations:
            for count in counts:
                group_key = f"{regime_name}__{formation}__{count}"
                rows_by_group[group_key] = []
                for seed in seeds:
                    cfg = PyBulletReplayConfig(
                        seed=seed,
                        num_uavs=count,
                        formation_type=formation,
                        **regime_kwargs,
                    )
                    cases, trace = generate_pybullet_replay_cases(cfg, case_prefix=regime_name)
                    rows = [evaluate_replay_case(case, method_config) for case in cases]
                    rows_by_regime[regime_name].extend(rows)
                    rows_by_group[group_key].extend(rows)
                    meta_runs.append(
                        {
                            "regime": regime_name,
                            "formation": formation,
                            "num_uavs": count,
                            "seed": seed,
                            "num_cases": len(rows),
                        }
                    )
                    if seed == seeds[0] and formation == formations[0]:
                        example_traces[f"{regime_name}_{count}"] = trace

    overall_rows = [row for rows in rows_by_regime.values() for row in rows]
    summary = {
        "overall": summarize_replay_results(overall_rows),
        "by_regime": {name: summarize_replay_results(rows) for name, rows in rows_by_regime.items()},
        "by_group": {name: summarize_replay_results(rows) for name, rows in rows_by_group.items()},
        "paired": {
            "overall_robust_bt_vs_ls": _paired_report(overall_rows, "robust_bias_trimmed", "least_squares"),
            "nominal_robust_bt_vs_ls": _paired_report(rows_by_regime["nominal_pybullet"], "robust_bias_trimmed", "least_squares"),
            "disturbed_robust_bt_vs_ls": _paired_report(rows_by_regime["disturbed_pybullet"], "robust_bias_trimmed", "least_squares"),
        },
    }

    payload = {
        "meta": {
            "source": "gym-pybullet-drones",
            "seeds": seeds,
            "formations": formations,
            "counts": counts,
            "regimes": regimes,
            "num_runs": len(meta_runs),
            "num_cases": len(overall_rows),
            "package_reference": "utiasDSL/gym-pybullet-drones",
            "bearing_generation_note": "A replayed bearing is generated from delayed observer pose, yaw-defined field of view, attitude and yaw-rate perturbations, slowly drifting bias, and stochastic missing/outlier events.",
        },
        "runs": meta_runs,
        "summary": summary,
    }
    traces_payload = {
        "meta": {
            "source": "gym-pybullet-drones",
            "selected_examples": list(example_traces.keys()),
        },
        "examples": example_traces,
    }

    (output_dir / "pybullet_replay_result.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    (output_dir / "pybullet_replay_traces.json").write_text(json.dumps(traces_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return payload


if __name__ == "__main__":
    result = run_pybullet_replay_validation()
    print(json.dumps(result["summary"], ensure_ascii=False, indent=2))
